version: '3.9'

networks:   
  frontend:
    external:
      name: frontend
  backend:
    external:
      name: backend

services:

  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: always
    depends_on:
      - traefik
    environment:
      - TZ=$TZ
    expose:
      - 9091
    volumes:
      - ./authelia:/config
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      - traefik.http.routers.authelia-rtrs.service=authelia
      - traefik.http.routers.authelia-rtrs.rule=Host(`$URL_AUTHELIA`)
      - traefik.http.routers.authelia-rtrs.entrypoints=websecure
      - traefik.http.routers.authelia-rtrs.tls=true
      - traefik.http.routers.authelia-rtrs.tls.certresolver=myresolver
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://$URL_AUTHELIA/
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email
      - traefik.docker.network=frontend

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ./bazarr/config:/config
      - /volume2/movies:/movies
      - /volume2/tvshows:/tv
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr-rtr.entrypoints=web
      - traefik.http.routers.bazarr-rtr.service=bazarr
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - traefik.http.routers.bazarr-rtr.rule=HostHeader(`$URL_BAZARR`)
      - traefik.http.routers.bazarr-rtr.middlewares=redirect-to-https
      - traefik.http.routers.bazarr-rtrs.middlewares=authelia@docker
      - traefik.http.routers.bazarr-rtrs.service=bazarr
      - traefik.http.routers.bazarr-rtrs.tls=true
      - traefik.http.routers.bazarr-rtrs.tls.certresolver=myresolver
      - traefik.http.routers.bazarr-rtrs.tls.domains[0].main=$URL_BAZARR
      - traefik.http.routers.bazarr-rtrs.entrypoints=websecure
      - traefik.http.routers.bazarr-rtrs.rule=HostHeader(`$URL_BAZARR`)

  calibreweb:
    image: linuxserver/calibre-web:latest
    container_name: calibreweb
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SET_CONTAINER_TIMEZONE=true
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ./calibreweb:/config
      - /volume1/ebooks:/books
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibreweb-rtr.entrypoints=web
      - traefik.http.routers.calibreweb-rtr.service=calibreweb
      - traefik.http.services.calibreweb.loadbalancer.server.port=8083
      - traefik.http.routers.calibreweb-rtr.rule=HostHeader(`$URL_CALIBREWEB`)
      - traefik.http.routers.calibreweb-rtr.middlewares=redirect-to-https
      - traefik.http.routers.calibreweb-rtrs.entrypoints=websecure
      - traefik.http.routers.calibreweb-rtrs.tls.domains[0].main=$URL_CALIBREWEB
      - traefik.http.routers.calibreweb-rtrs.tls=true
      - traefik.http.routers.calibreweb-rtrs.tls.certresolver=myresolver
      - traefik.http.routers.calibreweb-rtrs.service=calibreweb
      - traefik.http.routers.calibreweb-rtrs.rule=HostHeader(`$URL_CALIBREWEB`)

  git:
    image: gitea/gitea:latest
    container_name: git
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DB_TYPE=mysql
      - DB_HOST=mariadb:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=$DB_GITEA
      - DOMAIN=git.vanenter.nl
      - SSH_DOMAIN=git.vanenter.nl
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      - frontend
      - backend
    volumes:
      - ./git:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.git-rtr.entrypoints=web
      - traefik.http.routers.git-rtr.service=git
      - traefik.http.routers.git-rtr.rule=HostHeader(`$URL_GIT`)
      - traefik.http.routers.git-rtr.middlewares=redirect-to-https
      - traefik.http.routers.git-rtrs.entrypoints=websecure
      - traefik.http.routers.git-rtrs.service=git
      - traefik.http.routers.git-rtrs.tls=true
      - traefik.http.routers.git-rtrs.tls.certresolver=myresolver
      - traefik.http.routers.git-rtrs.tls.domains[0].main=$URL_GIT
      - traefik.http.routers.git-rtrs.rule=HostHeader(`$URL_GIT`)
      - traefik.http.services.git.loadbalancer.server.port=3000
      - traefik.tcp.routers.git-ssh.entrypoints=ssh
      - traefik.tcp.routers.git-ssh.tls=true
      - traefik.tcp.routers.git-ssh.tls.certresolver=myresolver
      - traefik.tcp.routers.git-ssh.tls.domains[0].main=$URL_GIT
      - traefik.tcp.routers.git-ssh.rule=HostSNI(`$URL_GIT`)
      - traefik.tcp.services.git-ssh.loadbalancer.server.port=22

  lidarr:
    image: ghcr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ./lidarr:/config
      - /volume1/audio/music:/music
      - /volume1/downloads/complete:/downloads
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.lidarr-rtr.entrypoints=web
      - traefik.http.routers.lidarr-rtr.service=lidarr
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - traefik.http.routers.lidarr-rtr.rule=HostHeader(`$URL_LIDARR`)
      - traefik.http.routers.lidarr-rtr.middlewares=redirect-to-https
      - traefik.http.routers.lidarr-rtrs.middlewares=authelia@docker
      - traefik.http.routers.lidarr-rtrs.service=lidarr
      - traefik.http.routers.lidarr-rtrs.tls=true
      - traefik.http.routers.lidarr-rtrs.tls.certresolver=myresolver
      - traefik.http.routers.lidarr-rtrs.tls.domains[0].main=$URL_LIDARR
      - traefik.http.routers.lidarr-rtrs.entrypoints=websecure
      - traefik.http.routers.lidarr-rtrs.rule=HostHeader(`$URL_LIDARR`)

  mariadb:
    image: ghcr.io/linuxserver/mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_ROOT_PASSWORD=$MYSQL_PWD
      - TZ=$TZ
    volumes:
      - ./mariadb:/config
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.tcp.routers.mariadb-rtr.rule=HostSNI(`*`)
      - traefik.tcp.routers.mariadb-rtr.entrypoints=mysql
      - traefik.tcp.routers.mariadb-rtr.service=mariadb
      - traefik.tcp.routers.mariadb-rtr.tls=false
      - traefik.tcp.services.mariadb.loadbalancer.server.port=3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - ./phpmyadmin/config.inc.php:/var/www/html/config.inc.php
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin-rtr.entrypoints=web
      - traefik.http.routers.phpmyadmin-rtr.service=phpmyadmin
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
      - traefik.http.routers.phpmyadmin-rtr.rule=HostHeader(`$URL_PHPMYADMIN`)
      - traefik.http.routers.phpmyadmin-rtr.middlewares=redirect-to-https
      - traefik.http.routers.phpmyadmin-rtrs.middlewares=authelia@docker
      - traefik.http.routers.phpmyadmin-rtrs.service=phpmyadmin
      - traefik.http.routers.phpmyadmin-rtrs.tls=true
      - traefik.http.routers.phpmyadmin-rtrs.tls.certresolver=myresolver
      - traefik.http.routers.phpmyadmin-rtrs.tls.domains[0].main=$URL_PHPMYADMIN
      - traefik.http.routers.phpmyadmin-rtrs.entrypoints=websecure
      - traefik.http.routers.phpmyadmin-rtrs.rule=HostHeader(`$URL_PHPMYADMIN`)
      - traefik.docker.network=frontend

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ./radarr:/config
      - /volume2/movies:/movies
      - /volume1/downloads/complete:/downloads
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr-rtr.entrypoints=web
      - traefik.http.routers.radarr-rtr.service=radarr
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr-rtr.rule=HostHeader(`$URL_RADARR`)
      - traefik.http.routers.radarr-rtr.middlewares=redirect-to-https
      - traefik.http.routers.radarr-rtrs.middlewares=authelia@docker
      - traefik.http.routers.radarr-rtrs.service=radarr
      - traefik.http.routers.radarr-rtrs.tls=true
      - traefik.http.routers.radarr-rtrs.tls.certresolver=myresolver
      - traefik.http.routers.radarr-rtrs.tls.domains[0].main=$URL_RADARR
      - traefik.http.routers.radarr-rtrs.entrypoints=websecure
      - traefik.http.routers.radarr-rtrs.rule=HostHeader(`$URL_RADARR`)

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./sabnzbd:/config
      - /volume1/downloads/complete:/downloads
      - /volume1/downloads/nzb_watch:/nzb_watch
      - /volume1/downloads/incomplete_sab:/incomplete-downloads
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd-rtr.entrypoints=web
      - traefik.http.routers.sabnzbd-rtr.service=sabnzbd
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
      - traefik.http.routers.sabnzbd-rtr.rule=HostHeader(`$URL_SABNZBD`)
      - traefik.http.routers.sabnzbd-rtr.middlewares=redirect-to-https
      - traefik.http.routers.sabnzbd-rtrs.middlewares=authelia@docker
      - traefik.http.routers.sabnzbd-rtrs.service=sabnzbd
      - traefik.http.routers.sabnzbd-rtrs.tls=true
      - traefik.http.routers.sabnzbd-rtrs.tls.certresolver=myresolver
      - traefik.http.routers.sabnzbd-rtrs.tls.domains[0].main=$URL_SABNZBD
      - traefik.http.routers.sabnzbd-rtrs.entrypoints=websecure
      - traefik.http.routers.sabnzbd-rtrs.rule=HostHeader(`$URL_SABNZBD`)

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ./sonarr:/config
      - /volume2/tvshows:/tv
      - /volume1/downloads/complete:/downloads
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr-rtr.entrypoints=web
      - traefik.http.routers.sonarr-rtr.service=sonarr
      - traefik.http.routers.sonarr-rtr.rule=HostHeader(`$URL_SONARR`)
      - traefik.http.routers.sonarr-rtr.middlewares=redirect-to-https
      - traefik.http.routers.sonarr-rtrs.entrypoints=websecure
      - traefik.http.routers.sonarr-rtrs.rule=HostHeader(`$URL_SONARR`)
      - traefik.http.routers.sonarr-rtrs.service=sonarr
      - traefik.http.routers.sonarr-rtrs.tls=true
      - traefik.http.routers.sonarr-rtrs.middlewares=authelia@docker
      - traefik.http.routers.sonarr-rtrs.tls.certresolver=myresolver
      - traefik.http.routers.sonarr-rtrs.tls.domains[0].main=$URL_SONARR

  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./syncthing/config:/config
      - /volume1/homes/Floris/Macbook/:/bkrMac
      - /volume1/homes/Floris/Cloud:/bkrMac/Cloud
      - /volume1/homes/Petra/:/ptrMac
      - /volume1/ebooks/:/common/ebooks
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.syncthing-rtr.entrypoints=web
      - traefik.http.routers.syncthing-rtr.service=syncthing
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
      - traefik.http.routers.syncthing-rtr.rule=HostHeader(`$URL_SYNCTHING`)
      - traefik.http.routers.syncthing-rtr.middlewares=redirect-to-https
      - traefik.http.routers.syncthing-rtrs.middlewares=authelia@docker
      - traefik.http.routers.syncthing-rtrs.tls.domains[0].main=$URL_SYNCTHING
      - traefik.http.routers.syncthing-rtrs.tls=true
      - traefik.http.routers.syncthing-rtrs.service=syncthing
      - traefik.http.routers.syncthing-rtrs.tls.certresolver=myresolver
      - traefik.http.routers.syncthing-rtrs.entrypoints=websecure
      - traefik.http.routers.syncthing-rtrs.rule=HostHeader(`$URL_SYNCTHING`)

  torrent:
    image: haugene/transmission-openvpn
    container_name: torrent
    volumes:
      - /volume1/downloads/complete:/data/completed
      - /volume1/downloads/incomplete:/data/incomplete
      - /volume1/downloads/torrent_watch:/data/watch
      - ./torrent/config:/config
      - ./torrent/data:/data
      - ./torrent/media:/media/share/Torrents
      - /etc/localtime:/etc/localtime:ro
    networks:
      - frontend
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=floris@entermi.nl
      - OPENVPN_PASSWORD=ment.maub3SECH4spot
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK= 172.20.99.0/24
      - NORDVPN_COUNTRY=CH
      - NORDVPN_PROTOCOL=tcp
      - NORDVPN_CATEGORY=legacy_p2p
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
    labels:
      - traefik.enable=true
      - traefik.http.routers.torrent-rtr.entrypoints=web
      - traefik.http.routers.torrent-rtr.service=torrent
      - traefik.http.services.torrent.loadbalancer.server.port=9091
      - traefik.http.routers.torrent-rtr.rule=HostHeader(`$URL_TORRENT`)
      - traefik.http.routers.torrent-rtr.middlewares=redirect-to-https
      - traefik.http.routers.torrent-rtrs.middlewares=authelia@docker
      - traefik.http.routers.torrent-rtrs.service=torrent
      - traefik.http.routers.torrent-rtrs.tls=true
      - traefik.http.routers.torrent-rtrs.tls.certresolver=myresolver
      - traefik.http.routers.torrent-rtrs.tls.domains[0].main=$URL_TORRENT
      - traefik.http.routers.torrent-rtrs.entrypoints=websecure
      - traefik.http.routers.torrent-rtrs.rule=HostHeader(`$URL_TORRENT`)

  traefik:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - 202:22
      - 80:80
      - 443:443
      - 3306:3306
      - 8080:8080
    command: 
      - --log.level=info
#      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules
      - --providers.file.watch=true
      - --entryPoints.ssh.address=:202
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entryPoints.mysql.address=:3306
      - --accesslog=true
      - --accesslog.filepath=/data/access.log
      - --certificatesResolvers.myresolver.acme.httpChallenge=true
#      - --certificatesResolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=web
      - --certificatesResolvers.myresolver.acme.email=floris@vanenter.nl
      - --certificatesResolvers.myresolver.acme.storage=/letsencrypt/acme.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/data:/data
      - ./traefik/letsencrypt:/letsencrypt
      - ./traefik/rules:/rules
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.rule=HostHeader(`$URL_TRAEFIK`)
      - traefik.http.routers.traefik-rtr.entrypoints=web
      - traefik.http.routers.traefik-rtr.service=api@internal
      - traefik.http.routers.traefik-rtr.middlewares=redirect-to-https
      - traefik.http.routers.traefik-rtrs.middlewares=authelia@docker
      - traefik.http.routers.traefik-rtrs.rule=HostHeader(`$URL_TRAEFIK`)
      - traefik.http.routers.traefik-rtrs.entrypoints=websecure
      - traefik.http.routers.traefik-rtrs.service=api@internal
      - traefik.http.routers.traefik-rtrs.tls=true
      - traefik.http.routers.traefik-rtrs.tls.domains[0].main=$URL_TRAEFIK
      - traefik.http.routers.traefik-rtrs.tls.certresolver=myresolver
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https