     
--entrypoints.web.address=:80
--entrypoints.web.http.redirections.entryPoint.to=websecure
--entrypoints.web.http.redirections.entryPoint.scheme=https
--entrypoints.websecure.address=:443

  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    
 clarkson:
    image: ghcr.io/linuxserver/clarkson
    container_name: clarkson
    environment:
      - PUID=1026
      - PGID=100
      - MYSQL_HOST=mariadb
      - MYSQL_USERNAME=clarkson
      - MYSQL_PASSWORD=9nG63pD6R6KMOQNG
      - ENABLE_REGISTRATIONS=false
      - TZ=Europe/Amsterdam
    ports:
      - 3003:3000
    restart: unless-stopped

    
    
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    network_mode: container:transmission-vpn
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./qbittorrent:/config
      - /volume1/downloads/complete:/downloads
    ports:
      - 8168:8168
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Amsterdam
      - UMASK_SET=002
      - WEBUI_PORT=8168

  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    networks:
      proxy:
        ipv4_address: 192.168.90.90
    ports:
      - 9091:9091
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./transmission/data:/data
      - ./transmission/config:/config
      - /volume1/downloads/complete:/downloads/completed
      - /volume1/downloads/incomplete:/downloads/incomplete
      - /volume1/downloads/torrent_watch:/downloads/watch
    environment:
      OPENVPN_PROVIDER: privado
      OPENVPN_USERNAME: nh06588jyujk
      OPENVPN_PASSWORD: vufs20srb5ip
      OPENVPN_CONFIG: "fra-008.vpn.privado.io"
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      LOCAL_NETWORK: services_default
      PUID: 1026
      PGID: 100
      TZ: Europe/Amsterdam
      UMASK_SET: 2
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_RPC_HOST_WHITELIST: "127.0.0.1,172.16.8.22"
      TRANSMISSION_RPC_PASSWORD: 'password'
      TRANSMISSION_RPC_USERNAME: 'user'
      TRANSMISSION_UMASK: 002
      TRANSMISSION_RATIO_LIMIT: 0.01
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_DOWN: 2000
      TRANSMISSION_ALT_SPEED_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_UP: 15
      TRANSMISSION_SPEED_LIMIT_DOWN: 6000
      TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
      TRANSMISSION_SPEED_LIMIT_UP: 30
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
      TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
      TRANSMISSION_WATCH_DIR: /downloads/watch
      TRANSMISSION_WATCH_DIR_ENABLED: "true"
      TRANSMISSION_DOWNLOAD_DIR: /downloads/completed
