version: '3.9'

networks:
  frontend:
    external:
      name: frontend
  appnet:
    external:
      name: appnet
      
services:

  calibre:
    image: ghcr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022 #optional
      - CLI_ARGS= #optional
    volumes:
      - ./calibre:/config
      - ./calibre/add_books:/books_add
      - /volume1/ebooks:/books
    ports:
      - 8082:8080
      - 8083:8081
    networks:
      - appnet

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    networks:
      - appnet
 
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    entrypoint: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    environment:
      - TZ=$TZ
    volumes:
      - ./redis:/data
    networks:
      - frontend
